export const APPOINTMENTS_SET_REQUEST = "APPOINTMENTS_SET_REQUEST";
export const APPOINTMENTS_SET_SUCCESS = "APPOINTMENTS_SET_SUCCESS";
export const APPOINTMENTS_SET_FAIL = "APPOINTMENTS_SET_FAIL";
export const APPOINTMENT_USER_SET = "APPOINTMENT_USER_SET";
