export const BARBER_LIST_REQUEST = "BARBER_LIST_REQUEST";
export const BARBER_LIST_SUCCESS = "BARBER_LIST_SUCCESS";
export const BARBER_LIST_FAIL = "BARBER_LIST_FAIL";
export const BARBER_USER_SET = "BARBER_USER_SET";
