export const SERVICE_LIST_REQUEST = "SERVICE_LIST_REQUEST";
export const SERVICE_LIST_SUCCESS = "SERVICE_LIST_SUCCESS";
export const SERVICE_LIST_FAIL = "SERVICE_LIST_FAIL";
export const SERVICE_USER_SET = "SERVICE_USER_SET";
export const SERVICE_USER_RESET = "SERVICE_USER_RESET";
