# Generated by Django 3.1.7 on 2021-03-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210317_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
